# Generated by Django 3.2.12 on 2022-05-18 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0004_auto_20220518_0957'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
